<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-12T04:02:11Z" name="Testing_Suite" finished-at="2022-10-12T04:02:28Z" duration-ms="17384">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:mindq.seleniumtrainingaugframework.runners.Runner@6a370f4]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2022-10-12T04:02:11Z" name="CucumberTest" finished-at="2022-10-12T04:02:28Z" duration-ms="17384">
      <class name="mindq.seleniumtrainingaugframework.runners.Runner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:mindq.seleniumtrainingaugframework.runners.Runner@6a370f4]" started-at="2022-10-12T09:32:11Z" name="setUpClass" finished-at="2022-10-12T09:32:12Z" duration-ms="693" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:mindq.seleniumtrainingaugframework.runners.Runner@6a370f4]" started-at="2022-10-12T09:32:12Z" name="feature" description="Runs Cucumber Feature" data-provider="features" finished-at="2022-10-12T09:32:28Z" duration-ms="15520" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Login Test Cases]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Values are not matching expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
	Values are not matching expected [false] but found [true]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
	Values are not matching expected [false] but found [true]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at mindq.seleniumtrainingaugframework.stepdefinitions.LoginStepDefinitions.user_should_see_error_message_on_the_screen(LoginStepDefinitions.java:63)
	at âœ½.Then User should see error message on the screen(Login.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method is-config="true" signature="setup()[pri:0, instance:mindq.seleniumtrainingaugframework.runners.Runner@6a370f4]" started-at="2022-10-12T09:32:28Z" name="setup" finished-at="2022-10-12T09:32:28Z" duration-ms="53" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:mindq.seleniumtrainingaugframework.runners.Runner@6a370f4]" started-at="2022-10-12T09:32:28Z" name="tearDownClass" finished-at="2022-10-12T09:32:28Z" duration-ms="857" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- mindq.seleniumtrainingaugframework.runners.Runner -->
    </test> <!-- CucumberTest -->
  </suite> <!-- Testing_Suite -->
</testng-results>
